name: authentication_repository
description: Dart package which manages the authentication domain.
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  http: ^0.13.4
  shared_preferences: ^2.0.13
  sqflite: ^2.0.2
  path: ^1.8.0
  equatable: ^2.0.0
  crypt: ^4.2.1
